#!/usr/bin/env bash
# Exports environment variables to be used on this project

export DATABASE_URL='mysql+mysqldb://starlit:starlit.22@localhost/app'
export MYSQL_HOST=localhost
export MYSQL_USER=starlit
export MYSQL_PWD=starlit.22
export MYSQL_DB=app

# Export python path.
export PYTHONPATH=`(pwd)`
